ORG 0H ;BLINKING LED CODE
	START:
		CPL P1.0
		ACALL WAIT
		SJMP START
	WAIT:
		MOV R4, #10H ;THIS IS THE REASON FOR INCREASING DELAY!!
	WAIT1:
		MOV R3, #00H
	WAIT2:
		MOV R2, #00H
	WAIT3:
		DJNZ R2, WAIT3
		DJNZ R3, WAIT2
		DJNZ R4, WAIT1
		RET
		
	END
		